### ISSUE TITLE
plugins => plugin 

### ISSUE THREAD

**Issue by twandylue** [StuartHsu/NeoVim#1]
https://github.com/StuartHsu/NeoVim/blob/332183e7f4ff7e6ecd23ce0e4e01b10e1deb2032/init.lua#L4

因為你的資料夾名稱是 `plugin`, 所以理論上 `require('plugins')` 應該會找不到正確檔資料夾

![Screen Shot 2022-09-16 at 06 09 00](https://user-images.githubusercontent.com/70478084/190517524-84116967-fc11-4f18-a413-6031f7e264c8.png)

**Comment by twandylue** [comment]
然後 lspconfig 的[設定檔案](https://github.com/StuartHsu/NeoVim/blob/master/plugin/lspconfig.rc.lua)又在 `plugin/ `之下, 如果沒找到正確檔案資料夾, lspconfig 應該也不會起作用

**Comment by StuartHsu** [comment]
這個 require('plugins')  是取這裡面的 plugins.lua 檔案
且狀況是 util.root_pattern 有在處理，只是處理噴 exception，註解掉就沒事，但找不到 root_pattern 而已
<img width="181" alt="image" src="https://user-images.githubusercontent.com/37326528/190520447-6fd7652e-3674-4102-bc04-7df4d541213d.png">

**Comment by twandylue** [comment]
原來如此
了解了！
